function FileStructureD = ImportXLSXData(workbookFile)
%IMPORTFILE Import data from a spreadsheet
%  FILESTRUCTURED = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  FILESTRUCTURED = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  FILESTRUCTURED = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  FileStructureD = importfile("C:\GitHub\YouTube\Matlab25\xlsx\FileStructure_D.xlsx", "Sheet1", [2, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Mar-2024 09:56:42

%% Input handling

% % If no sheet is specified, read first sheet
% if nargin == 1 || isempty(sheetName)
%     sheetName = 1;
% end
% 
% % If row start and end points are not specified, define defaults
% if nargin <= 2
%     dataLines = [2, 5];
% end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% % Specify sheet and range
% opts.Sheet = sheetName;
% opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["path", "file", "dateModified", "fileSize_kB", "criticalFile", "comment"];
opts.VariableTypes = ["categorical", "string", "datetime", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["file", "comment"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["path", "file", "comment"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "dateModified", "InputFormat", "");

% Import the data
FileStructureD = readtable(workbookFile, opts, "UseExcel", false);

% for idx = 2:size(dataLines, 1)
%     opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
%     tb = readtable(workbookFile, opts, "UseExcel", false);
%     FileStructureD = [FileStructureD; tb]; %#ok<AGROW>
% end

%Remove the first row from the table
FileStructureD = FileStructureD(2:end,:);
end