function FileStructureE = ImportCSVData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FILESTRUCTUREE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  FILESTRUCTUREE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  FileStructureE = importfile("C:\GitHub\YouTube\Matlab25\csv\FileStructure_E.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Mar-2024 10:16:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["path", "file", "dateModified", "fileSize_kB", "criticalFile", "comment"];
opts.VariableTypes = ["categorical", "string", "datetime", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["file", "comment"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["path", "file", "comment"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "dateModified", "InputFormat", "MM/dd/yy");

% Import the data
FileStructureE = readtable(filename, opts);

end